- hosts: all
  become: true
  become_method: sudo
  vars:
    ansible_ssh_pipelining: true

    # python configuration
    galaxy_virtualenv_command: /usr/bin/python3 -m virtualenv

    # postgresql configuration
    postgresql_version: 15
    postgresql_objects_users:
      - name: galaxy
    postgresql_objects_databases:
      - name: galaxy
        owner: galaxy
      - name: galaxy_tools
        owner: galaxy

    # Path configuration
    export_dir: /export
    database_path: '{{ export_dir }}/database'

    # Galaxy configuration
    galaxy_create_user: true
    galaxy_force_checkout: true
    galaxy_separate_privileges: yes
    galaxy_manage_paths: true
    galaxy_layout: root-dir
    galaxy_privsep_user: galaxy
    galaxy_user: { name: galaxy, shell: /bin/bash, uid: 5001 }
    galaxy_group: { name: galaxy, gid: 5001 }
    galaxy_root: /home/galaxy/galaxy
    galaxy_server_dir: '{{ galaxy_root }}/server'
    galaxy_mutable_config_dir: '{{ galaxy_root }}/config'
    galaxy_config_file: '{{ galaxy_mutable_config_dir }}/galaxy.yml'
    galaxy_commit_id: release_24.2
    galaxy_config_style: yaml
    galaxy_systemd_mode: 'gravity'

    galaxy_job_config:
      runners:
        local_runner:
          load: galaxy.jobs.runners.local:LocalJobRunner
          workers: 4
      handling:
        assign: ['db-skip-locked']
      execution:
        default: local_env
        environments:
          local_env:
            runner: local_runner
            tmp_dir: true
      tools:
        - class: local
          environment: local_env

    galaxy_config:
      galaxy:
        brand: "laniakea-express"
        admin_users: "admin@server.com"
        database_connection: "postgresql:///galaxy?host=/var/run/postgresql"
        install_database_connection: "postgresql:///galaxy_tools?host=/var/run/postgresql"
        check_migrate_tools: false
        allow_user_creation: "True"
        allow_user_impersonation: "True"
        new_user_dataset_access_role_default_private: "True"
        file_path: '{{ export_dir }}'
        tool_dependency_dir: '{{ export_dir }}/tool_deps'
        conda_prefix: '{{ export_dir }}/tool_deps/_conda'
        job_working_directory: '{{ export_dir }}/database/job_working_dir'
        galaxy_url_prefix: /galaxy
        job_config: "{{ galaxy_job_config }}"
        tus_upload_store: "{{ database_path }}/tus"
        galaxy_infrastructure_url: "https://{{ inventory_hostname }}/galaxy"
      gravity:
        process_manager: systemd
        galaxy_root: "{{ galaxy_root }}/server"
        galaxy_user: galaxy
        virtualenv: "{{ galaxy_root }}/venv"
        gunicorn:
          bind: "127.0.0.1:4001"
          workers: 2
          extra_args: '--forwarded-allow-ips="*"'
          preload: true
        celery:
          concurrency: 2
          loglevel: DEBUG
        handlers:
          handler:
            processes: 3
            pools:
              - job-handler
              - workflow-scheduler
        tusd:
          enable: true
          tusd_path: /usr/local/sbin/tusd
          upload_dir: "{{ export_dir }}/database/tus"

    # nginx
    nginx_selinux_allow_local_connections: true
    nginx_server_src_dir: /tmp/nginx_templates
    nginx_servers:
      - galaxy
    nginx_enable_default_server: false
    nginx_conf_http:
      client_max_body_size: 1g
      gzip: "on"
      gzip_proxied: "any"
      gzip_static: "on"
      gzip_vary: "on"
      gzip_min_length: 128
      gzip_comp_level: 6
      gzip_types: |
        text/plain
        text/css
        text/xml
        text/javascript
        application/javascript
        application/x-javascript
        application/json
        application/xml
        application/xml+rss
        application/xhtml+xml
        application/x-font-ttf
        application/x-font-opentype
        image/png
        image/svg+xml
        image/x-icon
    nginx_conf_user: galaxy
    nginx_conf_group: galaxy

    enable_galaxy_ie: false
    enable_interactive_tools: false

    # Miniconda
    miniconda_prefix: '{{ export_dir }}/tool_deps/_conda'
    miniconda_version: 25.7.0
    miniconda_channels: ['conda-forge', 'bioconda']

    # TUS
    galaxy_tusd_port: 1080

  pre_tasks:
    - name: 'Create shared ansible tmp directory'
      file:
        path: /tmp/.ansible-rocky
        state: directory
        mode: '0777'

    - name: 'Create galaxy group'
      group:
        name: galaxy
        gid: 5001
        state: present

    - name: 'Create galaxy user'
      user:
        name: galaxy
        group: galaxy
        uid: 5001
        home: /home/galaxy
        shell: /bin/bash
        create_home: true
        state: present

    - name: 'Create /export directory'
      file:
        path: /export
        state: directory
        owner: galaxy
        group: galaxy
        mode: '0755'

    - name: 'Create nginx templates directory'
      file:
        path: /tmp/nginx_templates
        state: directory
        mode: '0755'

    - name: 'Deploy nginx galaxy template'
      copy:
        dest: /tmp/nginx_templates/galaxy.j2
        mode: '0644'
        content: |
          upstream galaxy {
              server 127.0.0.1:4001;
          }
          server {
              listen        *:80 default_server;
              server_name   "{{ inventory_hostname }}";
              access_log  /var/log/nginx/access.log;
              error_log   /var/log/nginx/error.log;
              location /galaxy {
                  proxy_pass http://127.0.0.1:4001;
                  proxy_set_header Host $http_host;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
                  proxy_set_header Upgrade $http_upgrade;
              }
              location /galaxy/api/upload/resumable_upload {
                  proxy_request_buffering     off;
                  proxy_buffering             off;
                  proxy_http_version          1.1;
                  proxy_set_header X-Forwarded-Host   $host;
                  proxy_set_header X-Forwarded-Proto  $scheme;
                  proxy_set_header Upgrade            $http_upgrade;
                  proxy_set_header Connection         "upgrade";
                  client_max_body_size        0;
                  proxy_pass http://127.0.0.1:{{ galaxy_tusd_port }}/files;
              }
              location /galaxy/static {
                  alias {{ galaxy_server_dir }}/static;
                  expires 24h;
              }
              location /galaxy/static/welcome.html {
                  alias {{ galaxy_server_dir }}/static/welcome.sample.html;
                  expires 24h;
              }
              location ~ ^/plugins/(?<plug_type>[^/]+?)/((?<vis_d>[^/_]*)_?)?(?<vis_name>[^/]*?)/static/(?<static_file>.*?)$ {
                  alias {{ galaxy_server_dir }}/config/plugins/$plug_type/;
                  try_files $vis_d/${vis_d}_${vis_name}/static/$static_file
                            $vis_d/static/$static_file =404;
              }
              rewrite ^/galaxy$ /galaxy/ last;
              location /robots.txt {
                  alias {{ galaxy_server_dir }}/static/robots.txt;
              }
              location /favicon.ico {
                  alias {{ galaxy_server_dir }}/static/favicon.ico;
              }
              location /_x_accel_redirect {
                  internal;
                  alias /;
              }
              location /training-material/ {
                  proxy_pass https://training.galaxyproject.org/training-material/;
              }
          }

    - name: '[EL] Install Packages for Rocky Linux'
      ansible.builtin.dnf:
        name: ['langpacks-en', 'glibc-all-langpacks', 'epel-release', 'python3-wheel-wheel']
        enablerepo: crb
        state: present

    - name: Install python3-virtualenv
      yum:
        name: python3-virtualenv
        enablerepo: epel-release
        state: present

    - name: '[EL] Install Galaxy Dependencies'
      package:
        name: ['acl', 'bzip2', 'git', 'make', 'python-psycopg2', 'python3-psycopg2', 'tar', 'pip', 'gcc', 'openssl-devel', 'bzip2-devel', 'libffi-devel', 'zlib-devel', 'xz-devel', 'sqlite-devel', 'wget']

    - name: Install pgdg repository package (RedHat)
      yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        disable_gpg_check: True

    - name: '[EL] update ca-certificates'
      command: 'yum update -y ca-certificates'

    - name: '[EL] Disable SELinux'
      selinux:
        state: disabled

  roles:
    - galaxyproject.postgresql
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres
    - geerlingguy.pip
    - galaxyproject.tusd
    - galaxyproject.galaxy
    - role: galaxyproject.miniconda
      become: true
      become_user: galaxy
    - galaxyproject.nginx

  post_tasks:
    - name: 'Create /export'
      file:
        state: directory
        path: '{{ export_dir }}'
        owner: galaxy
        group: galaxy
        mode: '0755'

    - name: galaxyctl update
      command: "{{ galaxy_root }}/venv/bin/galaxyctl -c {{ galaxy_config_file }} update"

    - name: galaxy gravity restart
      command: "{{ galaxy_root }}/venv/bin/galaxyctl -c {{ galaxy_config_file }} graceful"

    - name: 'Wait Galaxy'
      wait_for:
        host: 127.0.0.1
        port: '4001'
        timeout: 15000

    - name: lock-file absent
      file:
        path: /export/tool_deps/conda.lock
        state: absent
